### ISSUE TITLE
Blog pagination bug

### ISSUE THREAD

**Issue by tonytoth** [7php/7php-website#1]
Hello.
While I tried to switch the page, on the blog, I figured out that there is a bug.
If you want to change the page, the URL is wrong.
Trying to access the 2nd page, the URL is: https://7php.comblog/page/2/
There is a missing "/" in URL.
If I modify to https://7php.com/blog/page/2/, it works.

**Comment by 7php** [comment]
Hey there @tonytoth, thank you very much for this report. It's indeed a bug.
I will have a look at fixing it and revert back to you on this ticket.

You are awesome! Would you like some stickers of 7PHP? Send me your physical address at w@7php.com and I'll make you it reaches you. :)

cheers

**Comment by 7php** [comment]
Hi @tonytoth 
I have fixed this bug. Please review and let me if all OK on your side: https://7php.com/blog/

PS: Do you have a twitter handle? I will give you a shoutout on twitter as well.

Thank for being awesome!
cheers

**Comment by tonytoth** [comment]
Hello Wasseem,
Unfortunately I don't have twitter.
Have a nice day,
Tony
